### ISSUE TITLE
Memory corruption in c_dvar_write_data()

### ISSUE THREAD

**Issue by floppym** [c-util/c-dvar#1]
In testing dbus-broker v3, I managed to crash it by logging into a KDE Plasma session via sddm.

Distro: Gentoo
GCC 6.4.0
glibc 2.25 (with some backports)
Linux kernel 4.9.34
c-dvar v1
dbus-broker v3

[gdb.txt](https://github.com/c-util/c-dvar/files/1248975/gdb.txt)

**Comment by dvdhrm** [comment]
Did you, by any chance, compile with `-O3`?

**Comment by floppym** [comment]
Nope.

c-dvar and dbus-broker were compiled with  `-O0 -g -pipe -march=amdfam10`. That why I was able to provide a detailed backtrace. ;-)

glibc and gcc were built with `-Og -g -pipe -march=amdfam10`.

Everything else on the system is compiled with `-O2 -pipe -march=amdfam10`.

**Comment by dvdhrm** [comment]
Your backtrace shows that this is a malloc corruption. It also appears to be triggered in the UpdateActivationEnvironment D-Bus call. So this is unlikely to be related to c-dvar directly.

I fixed something that I guess is the culprit: https://github.com/bus1/dbus-broker/commit/b08cc9dab51eab5a4b10c147ecd4cbd8efc238d6

If you run dbus-broker-git, this should no longer happen. If it does, please re-open!

Thanks a lot for the report!

**Comment by floppym** [comment]
It works!
