### ISSUE TITLE
Possible strict aliasing violation in src/c-dvar-reader.c

### ISSUE THREAD

**Issue by kostadinsh** [c-util/c-dvar#7]
GCC reports some violations of the strict-aliasing rules, not sure if the issue is valid, thought it should be reported just in case.

`CFLAGS="-O2 -Wstrict-aliasing=2" meson setup build`

```
[27/34] Compiling C object src/libcdvar-1.so.0.p/c-dvar-reader.c.o
../src/c-dvar-reader.c: In function ‘c_dvar_try_vread’:
../src/c-dvar-reader.c:223:69: warning: dereferencing type-punned pointer might break strict-aliasing rules [-Wstrict-aliasing]
  223 |                         r = c_dvar_read_data(var, 0, (const void **)&str, n);
      |                                                                     ^~~~
../src/c-dvar-reader.c:381:69: warning: dereferencing type-punned pointer might break strict-aliasing rules [-Wstrict-aliasing]
  381 |                         r = c_dvar_read_data(var, 0, (const void **)&str, u32);
      |   
```

**Comment by dvdhrm** [comment]
Thanks a lot for the report!

I certainly don't think this leads to any miscompilations, given that it would require a caller to access the variant-buffer with types other than c-dvar. But given that the buffer is well-encoded, there seems little reason to do so. However, if endian-wrappers are used, I can definitely see a scenario where this is technically a bug.

Having said that, I now adjusted the code to use `c_load_*()` from c-stdaux and thus avoid any aliasing issues. Furthermore, we explicitly pass `const char *` as data pointer, to ensure the compiler can track the type properly and no longer warns about the string-pointer aliasing.

If any issues remain, please let me know!
